export const SIDEBAR_COLLAPSED_WIDTH = 54;
export const SIDEBAR_EXPANDED_WIDTH = 220;

const themes = {
  light: {
    accent: "#0f6cbd",
    accentStrong: "#0b57a3",
    accentSoft: "linear-gradient(135deg, #d9ebff 0%, #edf6ff 100%)",
    rootBackground:
      "radial-gradient(circle at top right, rgba(111, 180, 255, 0.16), transparent 26%), radial-gradient(circle at bottom left, rgba(14, 111, 189, 0.08), transparent 24%), linear-gradient(180deg, #f7fbff 0%, #eef4fb 100%)",
    sidebarBackground:
      "linear-gradient(180deg, #0b4f94 0%, #0a66b8 52%, #0d7ccf 100%)",
    sidebarPanel: "rgba(255,255,255,0.16)",
    sidebarActive:
      "linear-gradient(135deg, rgba(255,255,255,0.22) 0%, rgba(255,255,255,0.14) 100%)",
    textOnAccent: "#ffffff",
    headerBackground: "rgba(255,255,255,0.78)",
    headerBorder: "rgba(190, 212, 236, 0.9)",
    headerShadow: "0 14px 30px rgba(41, 92, 148, 0.12)",
    primaryText: "#17304f",
    secondaryText: "#526d8e",
    mutedText: "#7088a6",
    subtleText: "#8196ae",
    softText: "#9baec4",
    panelBackground: "rgba(255,255,255,0.72)",
    panelBorder: "rgba(196, 218, 240, 0.95)",
    introBackground:
      "linear-gradient(135deg, rgba(255,255,255,0.92) 0%, rgba(236,245,255,0.88) 100%)",
    badgeBackground: "rgba(15,108,189,0.1)",
    badgeText: "#0f6cbd",
    noticeBackground:
      "linear-gradient(135deg, #0f6cbd 0%, #1b88d9 100%)",
    noticeText: "#ffffff",
    dropdownBackground: "rgba(255,255,255,0.92)",
    dropdownBorder: "rgba(199, 216, 236, 0.95)",
    dropdownShadow: "0 18px 36px rgba(30, 82, 135, 0.16)",
    cardBackground:
      "linear-gradient(180deg, rgba(255,255,255,0.94) 0%, rgba(248,251,255,0.96) 100%)",
    cardBorder: "rgba(206, 223, 243, 0.95)",
    cardShadow: "0 12px 28px rgba(31, 85, 138, 0.08)",
    cardHoverShadow: "0 20px 38px rgba(24, 91, 152, 0.16)",
    emptyBackground: "rgba(255,255,255,0.76)",
    emptyBorder: "rgba(172, 202, 234, 0.9)",
    servicePillBackground: "rgba(15,108,189,0.1)",
    servicePillText: "#0f6cbd",
    windowIcon: "#8ea3bb",
    hoverBackground: "rgba(15,108,189,0.08)",
    orbPrimary: "rgba(74, 160, 255, 0.2)",
    orbSecondary: "rgba(15, 108, 189, 0.12)",
    glassBlur: "blur(14px)",
  },
  dark: {
    accent: "#7ec1ff",
    accentStrong: "#50a7ff",
    accentSoft: "linear-gradient(135deg, #17314d 0%, #10253d 100%)",
    rootBackground:
      "radial-gradient(circle at top right, rgba(88, 170, 255, 0.18), transparent 24%), radial-gradient(circle at bottom left, rgba(35, 93, 156, 0.16), transparent 20%), linear-gradient(180deg, #07111f 0%, #0a1424 100%)",
    sidebarBackground:
      "linear-gradient(180deg, #071120 0%, #0b1d33 52%, #0e2947 100%)",
    sidebarPanel: "rgba(255,255,255,0.08)",
    sidebarActive:
      "linear-gradient(135deg, rgba(126,193,255,0.2) 0%, rgba(126,193,255,0.12) 100%)",
    textOnAccent: "#edf6ff",
    headerBackground: "rgba(13, 22, 38, 0.76)",
    headerBorder: "rgba(34, 53, 81, 0.9)",
    headerShadow: "0 18px 34px rgba(0,0,0,0.35)",
    primaryText: "#edf5ff",
    secondaryText: "#bfd0e4",
    mutedText: "#8ea7c6",
    subtleText: "#7892b2",
    softText: "#667c99",
    panelBackground: "rgba(15, 26, 44, 0.76)",
    panelBorder: "rgba(34, 53, 81, 0.95)",
    introBackground:
      "linear-gradient(135deg, rgba(15,26,44,0.88) 0%, rgba(10,19,34,0.84) 100%)",
    badgeBackground: "rgba(126,193,255,0.12)",
    badgeText: "#8fcbff",
    noticeBackground:
      "linear-gradient(135deg, #0f4f86 0%, #1769ab 100%)",
    noticeText: "#edf5ff",
    dropdownBackground: "rgba(15, 26, 44, 0.92)",
    dropdownBorder: "rgba(39, 60, 89, 0.95)",
    dropdownShadow: "0 22px 42px rgba(0,0,0,0.38)",
    cardBackground:
      "linear-gradient(180deg, rgba(16,29,48,0.94) 0%, rgba(10,20,35,0.98) 100%)",
    cardBorder: "rgba(39, 60, 89, 0.95)",
    cardShadow: "0 12px 26px rgba(0,0,0,0.22)",
    cardHoverShadow: "0 22px 38px rgba(0,0,0,0.34)",
    emptyBackground: "rgba(15, 26, 44, 0.8)",
    emptyBorder: "rgba(62, 91, 128, 0.9)",
    servicePillBackground: "rgba(126,193,255,0.12)",
    servicePillText: "#90ccff",
    windowIcon: "#6f84a2",
    hoverBackground: "rgba(126,193,255,0.1)",
    orbPrimary: "rgba(59, 126, 209, 0.2)",
    orbSecondary: "rgba(15, 82, 139, 0.18)",
    glassBlur: "blur(16px)",
  },
};

export function getStyles(mode = "light") {
  const theme = themes[mode] ?? themes.light;

  return {
    root: {
      display: "flex",
      minHeight: "100vh",
      fontFamily: "'Segoe UI', 'Roboto', sans-serif",
      background: theme.rootBackground,
      color: theme.primaryText,
      transition: "background 0.25s ease, color 0.25s ease",
    },
    sidebar: {
      background: theme.sidebarBackground,
      display: "flex",
      flexDirection: "column",
      alignItems: "stretch",
      padding: "12px 4px 14px",
      gap: 10,
      position: "fixed",
      top: 0,
      left: 0,
      height: "100vh",
      zIndex: 100,
      boxShadow: "10px 0 28px rgba(0,0,0,0.16)",
      transition: "width 0.22s ease, background 0.25s ease",
      overflow: "hidden",
    },
    sideLogoWrap: {
      marginBottom: 10,
      display: "flex",
      justifyContent: "center",
    },
    sideLogo: {
      fontSize: 24,
      background: theme.sidebarPanel,
      backdropFilter: theme.glassBlur,
      borderRadius: 14,
      width: 40,
      height: 40,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.12)",
    },
    sideNav: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
      width: "100%",
      flex: 1,
    },
    sideNavButton: {
      width: "100%",
      minHeight: 48,
      borderRadius: 14,
      border: "none",
      outline: "none",
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-start",
      gap: 12,
      cursor: "pointer",
      transition: "background 0.2s, transform 0.18s, color 0.18s",
      background: "transparent",
      color: theme.textOnAccent,
      padding: "8px 6px",
    },
    sideNavButtonActive: {
      background: theme.sidebarActive,
      transform: "translateY(-1px)",
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.1)",
    },
    sideNavIcon: {
      fontSize: 17,
      lineHeight: 1,
      minWidth: 18,
      textAlign: "center",
    },
    sideNavLabel: {
      fontSize: 12,
      fontWeight: 700,
      textAlign: "left",
      lineHeight: 1.2,
      whiteSpace: "nowrap",
      transition: "opacity 0.16s ease",
      letterSpacing: 0.2,
    },
    main: {
      marginLeft: SIDEBAR_COLLAPSED_WIDTH,
      flex: 1,
      display: "flex",
      flexDirection: "column",
      position: "relative",
      overflow: "hidden",
    },
    mainBackdrop: {
      position: "absolute",
      inset: 0,
      pointerEvents: "none",
      overflow: "hidden",
    },
    backdropGlowPrimary: {
      position: "absolute",
      top: -90,
      right: -40,
      width: 280,
      height: 280,
      borderRadius: "50%",
      background: theme.orbPrimary,
      filter: "blur(40px)",
    },
    backdropGlowSecondary: {
      position: "absolute",
      bottom: 80,
      left: 60,
      width: 220,
      height: 220,
      borderRadius: "50%",
      background: theme.orbSecondary,
      filter: "blur(50px)",
    },
    contentLayer: {
      position: "relative",
      zIndex: 1,
      display: "flex",
      flexDirection: "column",
      minHeight: "100vh",
    },
    header: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      background: theme.headerBackground,
      borderBottom: `1px solid ${theme.headerBorder}`,
      padding: "0 24px",
      height: 68,
      position: "sticky",
      top: 0,
      zIndex: 50,
      boxShadow: theme.headerShadow,
      backdropFilter: theme.glassBlur,
    },
    headerLeft: {
      flex: 1,
    },
    menuBtn: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      background: theme.badgeBackground,
      border: "none",
      cursor: "pointer",
      fontSize: 14,
      color: theme.primaryText,
      fontWeight: 700,
      padding: "10px 14px",
      borderRadius: 999,
      transition: "background 0.15s, transform 0.15s",
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.1)",
    },
    hamburger: {
      fontSize: 18,
      color: theme.accent,
    },
    menuText: {
      color: theme.primaryText,
    },
    menuArrow: {
      fontSize: 10,
      color: theme.subtleText,
    },
    headerCenter: {
      flex: 2,
      display: "flex",
      justifyContent: "center",
    },
    logoBlock: {
      display: "flex",
      alignItems: "center",
      gap: 12,
    },
    logoTextBlock: {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-end",
      lineHeight: 1.12,
    },
    logoIIT: {
      fontWeight: 900,
      fontSize: 24,
      color: theme.accentStrong,
      letterSpacing: 2.4,
    },
    logoSub: {
      fontSize: 11.5,
      color: theme.secondaryText,
      fontWeight: 700,
      letterSpacing: 0.6,
    },
    logoTagline: {
      fontSize: 9.5,
      color: theme.mutedText,
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    logoMotto: {
      fontSize: 9,
      color: theme.softText,
      fontStyle: "italic",
    },
    logoBadge: {
      fontSize: 34,
      filter: "drop-shadow(0 4px 10px rgba(0,0,0,0.08))",
    },
    headerRight: {
      flex: 1,
      display: "flex",
      justifyContent: "flex-end",
    },
    userBlock: {
      display: "flex",
      alignItems: "center",
      gap: 12,
    },
    themeToggle: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      background: theme.badgeBackground,
      color: theme.badgeText,
      border: "none",
      borderRadius: 999,
      padding: "9px 14px",
      cursor: "pointer",
      fontSize: 12,
      fontWeight: 800,
      letterSpacing: 0.2,
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.1)",
    },
    windowIcons: {
      display: "flex",
      gap: 4,
      background: theme.badgeBackground,
      borderRadius: 999,
      padding: "8px 10px",
    },
    windowIcon: {
      fontSize: 14,
      color: theme.windowIcon,
      cursor: "pointer",
    },
    userName: {
      fontSize: 13,
      fontWeight: 700,
      color: theme.primaryText,
      letterSpacing: 0.5,
    },
    userAvatar: {
      width: 38,
      height: 38,
      borderRadius: "50%",
      background: `linear-gradient(135deg, ${theme.accentStrong} 0%, ${theme.accent} 100%)`,
      color: "#fff",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontWeight: 700,
      fontSize: 13,
      letterSpacing: 0.5,
      boxShadow: "0 10px 18px rgba(0,0,0,0.14)",
    },
    dropdown: {
      position: "absolute",
      top: 76,
      background: theme.dropdownBackground,
      border: `1px solid ${theme.dropdownBorder}`,
      borderRadius: 18,
      boxShadow: theme.dropdownShadow,
      zIndex: 200,
      minWidth: 280,
      padding: "12px 0",
      display: "flex",
      flexDirection: "column",
      backdropFilter: theme.glassBlur,
    },
    dropdownTitle: {
      fontSize: 11,
      fontWeight: 800,
      color: theme.mutedText,
      textTransform: "uppercase",
      letterSpacing: 1,
      padding: "0 20px 10px",
    },
    dropdownItem: {
      border: "none",
      width: "calc(100% - 16px)",
      display: "flex",
      alignItems: "center",
      gap: 12,
      padding: "12px 20px",
      cursor: "pointer",
      transition: "background 0.13s, transform 0.13s",
      borderRadius: 12,
      margin: "1px 8px",
      textAlign: "left",
    },
    dropdownIcon: {
      fontSize: 18,
      width: 26,
      textAlign: "center",
    },
    dropdownLabel: {
      fontSize: 14,
      color: theme.primaryText,
      fontWeight: 600,
    },
    pageIntro: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "stretch",
      gap: 18,
      margin: "24px 24px 0",
      padding: "24px 24px 20px",
      background: theme.introBackground,
      border: `1px solid ${theme.panelBorder}`,
      borderRadius: 28,
      boxShadow: theme.headerShadow,
      backdropFilter: theme.glassBlur,
    },
    introContent: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      gap: 14,
    },
    introBadge: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      padding: "7px 12px",
      borderRadius: 999,
      background: theme.badgeBackground,
      color: theme.badgeText,
      fontSize: 12,
      fontWeight: 800,
      width: "fit-content",
      letterSpacing: 0.2,
    },
    greenDot: {
      color: "#22c55e",
      fontSize: 14,
    },
    introTitle: {
      margin: 0,
      fontSize: 34,
      color: theme.primaryText,
      letterSpacing: -0.8,
    },
    introText: {
      margin: 0,
      fontSize: 14.5,
      color: theme.secondaryText,
      maxWidth: 620,
      lineHeight: 1.65,
    },
    introStats: {
      display: "flex",
      flexWrap: "wrap",
      gap: 12,
    },
    introStat: {
      minWidth: 140,
      background: theme.panelBackground,
      border: `1px solid ${theme.panelBorder}`,
      borderRadius: 18,
      padding: "14px 14px 12px",
      boxShadow: "0 10px 20px rgba(0,0,0,0.06)",
      display: "flex",
      flexDirection: "column",
      gap: 8,
    },
    introStatTop: {
      display: "flex",
      alignItems: "center",
      gap: 8,
    },
    introStatIcon: {
      width: 28,
      height: 28,
      borderRadius: 10,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: theme.badgeBackground,
      color: theme.accentStrong,
      fontSize: 13,
      fontWeight: 800,
    },
    introStatLabel: {
      fontSize: 10.5,
      fontWeight: 800,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      color: theme.mutedText,
    },
    introStatValue: {
      display: "block",
      fontSize: 18,
      fontWeight: 900,
      color: theme.primaryText,
      lineHeight: 1.1,
    },
    introStatHelper: {
      display: "block",
      fontSize: 12,
      color: theme.mutedText,
      lineHeight: 1.4,
    },
    introMetaCard: {
      minWidth: 220,
      background: theme.panelBackground,
      borderRadius: 22,
      border: `1px solid ${theme.panelBorder}`,
      padding: "20px 22px",
      boxShadow: "0 18px 34px rgba(0,0,0,0.08)",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
    },
    introMetaLabel: {
      display: "block",
      fontSize: 11,
      color: theme.mutedText,
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 10,
      fontWeight: 800,
    },
    introMetaValue: {
      display: "block",
      fontSize: 34,
      color: theme.accentStrong,
      fontWeight: 900,
      lineHeight: 1,
    },
    introMetaHelper: {
      display: "block",
      fontSize: 12,
      color: theme.mutedText,
      marginTop: 8,
      lineHeight: 1.5,
    },
    noticeBar: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      background: theme.noticeBackground,
      color: theme.noticeText,
      padding: "12px 18px",
      margin: "16px 24px 0",
      borderRadius: 18,
      fontSize: 13.5,
      fontWeight: 600,
      letterSpacing: 0.1,
      boxShadow: "0 16px 28px rgba(13, 78, 135, 0.18)",
    },
    noticeText: {
      flex: 1,
      textAlign: "center",
      lineHeight: 1.5,
    },
    noticeClose: {
      background: "rgba(255,255,255,0.14)",
      border: "none",
      color: theme.noticeText,
      width: 32,
      height: 32,
      borderRadius: "50%",
      fontSize: 15,
      cursor: "pointer",
      marginLeft: 12,
    },
    gridSection: {
      padding: "20px 24px 32px",
    },
    modulePageSection: {
      padding: "24px",
      display: "flex",
      flexDirection: "column",
      gap: 18,
    },
    modulePageToolbar: {
      display: "flex",
      alignItems: "center",
      gap: 16,
    },
    modulePageBackButton: {
      border: "none",
      borderRadius: 999,
      padding: "10px 16px",
      background: theme.badgeBackground,
      color: theme.badgeText,
      fontWeight: 800,
      cursor: "pointer",
    },
    modulePageMeta: {
      display: "flex",
      flexDirection: "column",
      gap: 4,
    },
    modulePageCaption: {
      fontSize: 11,
      fontWeight: 800,
      letterSpacing: 0.9,
      textTransform: "uppercase",
      color: theme.mutedText,
    },
    modulePageTitle: {
      margin: 0,
      fontSize: 28,
      color: theme.primaryText,
    },
    gridSurface: {
      background: theme.panelBackground,
      border: `1px solid ${theme.panelBorder}`,
      borderRadius: 26,
      padding: "22px",
      boxShadow: theme.headerShadow,
      backdropFilter: theme.glassBlur,
    },
    gridHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 20,
    },
    gridTitle: {
      margin: 0,
      fontSize: 22,
      color: theme.primaryText,
      letterSpacing: -0.3,
    },
    gridDescription: {
      margin: "6px 0 0",
      fontSize: 13.5,
      color: theme.mutedText,
      lineHeight: 1.5,
    },
    serviceCount: {
      background: theme.servicePillBackground,
      color: theme.servicePillText,
      fontWeight: 800,
      fontSize: 12,
      padding: "9px 14px",
      borderRadius: 999,
      letterSpacing: 0.2,
    },
    emptyState: {
      background: theme.emptyBackground,
      border: `1px dashed ${theme.emptyBorder}`,
      color: theme.mutedText,
      borderRadius: 20,
      padding: "32px",
      textAlign: "center",
      fontWeight: 600,
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(170px, 1fr))",
      gap: 18,
    },
    card: {
      background: theme.cardBackground,
      borderRadius: 22,
      border: `1px solid ${theme.cardBorder}`,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: "26px 14px 20px",
      gap: 14,
      cursor: "pointer",
      transition: "transform 0.2s, box-shadow 0.2s, background 0.2s",
      boxShadow: theme.cardShadow,
      position: "relative",
      overflow: "hidden",
      textAlign: "center",
    },
    cardActive: {
      boxShadow: theme.cardHoverShadow,
      border: `1px solid ${theme.accentStrong}`,
      transform: "translateY(-2px)",
    },
    cardIcon: {
      fontSize: 34,
      background: theme.accentSoft,
      borderRadius: 18,
      width: 68,
      height: 68,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.18)",
    },
    cardLabel: {
      fontSize: 13,
      color: theme.primaryText,
      fontWeight: 700,
      textAlign: "center",
      lineHeight: 1.35,
      maxWidth: 140,
    },
    workspaceShell: {
      background: theme.cardBackground,
      border: `1px solid ${theme.cardBorder}`,
      borderRadius: 24,
      padding: "22px",
      marginBottom: 20,
      boxShadow: theme.cardShadow,
      display: "flex",
      flexDirection: "column",
      gap: 18,
    },
    workspaceHeader: {
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 16,
    },
    workspaceEyebrow: {
      display: "inline-block",
      fontSize: 11,
      fontWeight: 800,
      letterSpacing: 0.9,
      textTransform: "uppercase",
      color: theme.mutedText,
      marginBottom: 8,
    },
    workspaceTitle: {
      margin: 0,
      fontSize: 24,
      color: theme.primaryText,
    },
    workspaceText: {
      margin: "8px 0 0",
      fontSize: 14,
      color: theme.secondaryText,
      lineHeight: 1.6,
      maxWidth: 700,
    },
    workspaceStatus: {
      background: theme.servicePillBackground,
      color: theme.servicePillText,
      borderRadius: 999,
      padding: "8px 14px",
      fontSize: 12,
      fontWeight: 800,
      whiteSpace: "nowrap",
    },
    workspaceActions: {
      display: "flex",
      flexWrap: "wrap",
      gap: 12,
    },
    workspaceActionMessage: {
      background: theme.badgeBackground,
      color: theme.badgeText,
      borderRadius: 14,
      padding: "12px 14px",
      fontSize: 13,
      fontWeight: 700,
    },
    workspaceTabs: {
      display: "flex",
      flexWrap: "wrap",
      gap: 10,
    },
    workspaceTab: {
      border: "none",
      borderRadius: 999,
      padding: "9px 14px",
      background: theme.badgeBackground,
      color: theme.secondaryText,
      fontWeight: 700,
      textTransform: "capitalize",
      cursor: "pointer",
    },
    workspaceTabActive: {
      background: theme.servicePillBackground,
      color: theme.servicePillText,
    },
    workspacePrimaryAction: {
      border: "none",
      borderRadius: 999,
      padding: "11px 18px",
      background: `linear-gradient(135deg, ${theme.accentStrong} 0%, ${theme.accent} 100%)`,
      color: "#ffffff",
      fontWeight: 800,
      cursor: "pointer",
    },
    workspaceSecondaryAction: {
      border: `1px solid ${theme.panelBorder}`,
      borderRadius: 999,
      padding: "11px 18px",
      background: theme.panelBackground,
      color: theme.primaryText,
      fontWeight: 700,
      cursor: "pointer",
    },
    workspaceMetrics: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
      gap: 14,
    },
    workspaceMetricCard: {
      background: theme.badgeBackground,
      borderRadius: 18,
      padding: "14px 16px",
      display: "flex",
      flexDirection: "column",
      gap: 6,
    },
    workspaceMetricLabel: {
      fontSize: 11,
      fontWeight: 800,
      color: theme.mutedText,
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    workspaceMetricValue: {
      fontSize: 18,
      fontWeight: 800,
      color: theme.primaryText,
    },
    workspaceChecklist: {
      display: "flex",
      flexDirection: "column",
      gap: 10,
    },
    workspaceSplitGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
      gap: 16,
    },
    workspacePanel: {
      background: theme.panelBackground,
      border: `1px solid ${theme.panelBorder}`,
      borderRadius: 18,
      padding: "16px",
      display: "flex",
      flexDirection: "column",
      gap: 12,
    },
    workspaceChecklistTitle: {
      fontSize: 13,
      fontWeight: 800,
      color: theme.primaryText,
    },
    workspaceChecklistItem: {
      display: "flex",
      alignItems: "flex-start",
      gap: 10,
      color: theme.secondaryText,
      lineHeight: 1.5,
    },
    workspaceChecklistBullet: {
      color: theme.accentStrong,
      fontWeight: 900,
      lineHeight: 1.2,
    },
    workspaceLinkItem: {
      display: "flex",
      alignItems: "center",
      gap: 10,
      color: theme.secondaryText,
      lineHeight: 1.5,
    },
    workspaceLinkBullet: {
      color: theme.accentStrong,
      fontWeight: 900,
    },
    workspaceChecklistToggle: {
      border: `1px solid ${theme.panelBorder}`,
      borderRadius: 14,
      background: theme.cardBackground,
      padding: "12px 14px",
      display: "flex",
      alignItems: "center",
      gap: 10,
      color: theme.primaryText,
      textAlign: "left",
      cursor: "pointer",
    },
    workspaceChecklistToggleDone: {
      background: theme.servicePillBackground,
      color: theme.servicePillText,
    },
    workspaceChecklistToggleIcon: {
      fontWeight: 900,
      minWidth: 16,
    },
    workspaceUpdateItem: {
      display: "flex",
      alignItems: "flex-start",
      gap: 10,
      color: theme.secondaryText,
      lineHeight: 1.6,
    },
    workspaceUpdateBullet: {
      color: theme.accentStrong,
      fontWeight: 900,
    },
    cardHoverShadow: theme.cardHoverShadow,
    themeHoverBackground: theme.hoverBackground,
  };
}
